# lightning.pytorch==2.0.2
seed_everything: 5479
trainer:
  max_epochs: 1000
  num_nodes: 1
  accelerator: auto
  strategy: auto
  devices: auto
  precision: 32-true
  logger: false
  log_every_n_steps: 1
  check_val_every_n_epoch: 1
  enable_checkpointing: false
  enable_progress_bar: false
  reload_dataloaders_every_n_epochs: 1
  enable_model_summary: false

model:
  config:
    learning_rate: 0.01
    activation_function: SiLU
    n_sequential_blocks: 15
    n_hidden_units: 30
    dropout_rate: 0.1
    batch_normalization: true
    use_skip_connections: false
    evaluation_grid_size: 50

data:
  data_config:
    batch_size: 32
    n_time_bins: 20
    discretization_scheme: number
  seed: 5479

callbacks:
  early_stopping:
    monitor: val_loss
    patience: 10
